#!/bin/bash


# Set decoration geometry
berryc border_width       2
berryc inner_border_width 1
berryc title_height       0
berryc top_gap            27

# Set decoration colors
berryc focus_color         817f7f 
berryc unfocus_color       30302f
berryc inner_focus_color   4c4b4b
berryc inner_unfocus_color 002b36
berryc text_focus_color    4C566A
berryc text_unfocus_color  4C566A

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "tewi-medium"



sxhkd
